[General]
Autosave = 0
DisplayPerfInTitle = 0
ExtendedAspectRatio = 16:9
DisableFrameDelay = 0

[Graphics]
WindowSize = Auto
Fullscreen = 1
WindowScale = 3
NewRenderer = 1
EnhancedMode7 = 1
IgnoreAspectRatio = 0
NoSpriteLimits = 1
OutputMethod = SDL
LinearFiltering = 0
Shader =
DimFlashes = 0

[Sound]
EnableAudio = 1
# opuz playback requires 48000
AudioFreq = 48000
AudioChannels = 2
AudioSamples = 512
EnableMSU = deluxe-opuz
MSUPath = msu/ALttP-msu-Deluxe-
ResumeMSU = 1
MSUVolume = 100%

[Features]
ItemSwitchLR = 1
ItemSwitchLRLimit = 0
TurnWhileDashing = 1
MirrorToDarkworld = 0
CollectItemsWithSword = 0
BreakPotsWithSword = 0
DisableLowHealthBeep = 0
SkipIntroOnKeypress = 0
ShowMaxItemsInYellow = 0
MoreActiveBombs = 1
CarryMoreRupees = 1
MiscBugFixes = 1
GameChangingBugFixes = 0
CancelBirdTravel = 0

[KeyMap]
Controls = Up, Down, Left, Right, Right Shift, Return, x, z, s, a, c, v
Turbo = Tab
Pause = Shift+p
PauseDimmed = p
Reset = Ctrl+r
Fullscreen = Alt+Return
Load =      F1,     F2,     F3,     F4,     F5,     F6,     F7,     F8,     F9,     F10
Save = Shift+F1,Shift+F2,Shift+F3,Shift+F4,Shift+F5,Shift+F6,Shift+F7,Shift+F8,Shift+F9,Shift+F10

[GamepadMap]
Controls = DpadUp, DpadDown, DpadLeft, DpadRight, Back, Start, B, A, Y, X, Lb, Rb
