music_directory    "/home/@USER@/Music"
playlist_directory "/home/@USER@/Music/playlists"
bind_to_address    "/home/@USER@/.config/mpd/socket"

db_file            "/home/@USER@/.local/share/mpd/database"
state_file         "/home/@USER@/.local/share/mpd/state"
sticker_file       "/home/@USER@/.local/share/mpd/sticker.sql"
pid_file           "/home/@USER@/.local/share/mpd/pid"

audio_output {
  type "pipewire"
  name "PipeWire Sound Server"
}
