[shorturls]
gh = "github:{path}"
cb = "git+https://codeberg.org/{path}"

[inputs.nixpkgs]
url = "gh:NixOS/nixpkgs/nixos-unstable"

# Not followed -- the cached build is keyed to its own pinned nixpkgs; following forces a local recompile.
[inputs.nix-cachyos-kernel]
url = "gh:xddxdd/nix-cachyos-kernel/release"

[inputs.agenix]
url = "gh:ryantm/agenix"
follows = { nixpkgs = "nixpkgs" }

[inputs.preservation]
url = "gh:nix-community/preservation"

[inputs.hjem]
url = "gh:feel-co/hjem"
follows = { nixpkgs = "nixpkgs" }

[inputs.noctalia-qs]
url = "gh:noctalia-dev/noctalia-qs"
follows = { nixpkgs = "nixpkgs" }

[inputs.noctalia-shell]
url = "gh:noctalia-dev/noctalia-shell"
follows = { nixpkgs = "nixpkgs", noctalia-qs = "noctalia-qs" }

[inputs.lix]
url = "git+https://git.lix.systems/lix-project/lix"
type = "fetch"

[inputs.lix-module]
url = "git+https://git.lix.systems/lix-project/nixos-module"
follows = { lix = "lix", nixpkgs = "nixpkgs" }

[inputs.nix-index-database]
url = "gh:nix-community/nix-index-database"
follows = { nixpkgs = "nixpkgs" }

[inputs.pkgs]
url = "cb:weegs710/pkgs"
follows = { nixpkgs = "nixpkgs" }

[inputs.tack]
url = "gh:manic-systems/tack"
