# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  d2launcher = {
    pname = "d2launcher";
    version = "4.1.3";
    src = fetchFromGitHub {
      owner = "murkl";
      repo = "d2launcher";
      rev = "4.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-yK3ZYqeadh8AZ7q3TENdecAicGkBhSjZKlGUsBmzoMo=";
    };
  };
  helium = {
    pname = "helium";
    version = "0.14.8.2";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.14.8.2/helium-0.14.8.2-x86_64_linux.tar.xz";
      sha256 = "sha256-3XUwBw9sSQgPjTVX3oBGwK9PQXgN5J+ktdICey67wAE=";
    };
  };
  zen = {
    pname = "zen";
    version = "1.21.8b";
    src = fetchurl {
      url = "https://github.com/zen-browser/desktop/releases/download/1.21.8b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-BaNmV+TJ2+cA5UouOUH3r0ZWq74zBpCqdNjPeTrzlvQ=";
    };
  };
}
