{inputs, ...}: {
  flake.nixosModules.endcord = {
    config,
    lib,
    pkgs,
    ...
  }: let
    username = config.mySystem.user.name;
    wrappedEndcord = inputs.self.packages.${pkgs.stdenv.hostPlatform.system}.endcord;
  in {
    config = lib.mkIf config.mySystem.features.desktop {
      users.users.${username}.packages = [wrappedEndcord];

      # Declarative configuration management
      hjem.users.${username} = {
        xdg.config.files."endcord/config.ini".text = ''
          [main]
          theme = None
          extensions = True
          rpc = True
          game_detection = False
          vim_mode = False
          limit_chat_buffer = 100
          limit_channel_cache = 5
          download_msg = 25
          convert_timezone = True
          send_typing = True
          desktop_notifications = True
          notification_in_active = False
          remove_previous_notification = True
          ack_throttling = 5
          member_list = True
          member_list_auto_open = False
          use_nick_when_available = True
          remember_state = True
          remember_tabs = True
          reply_mention = True
          cache_typed = True
          show_pending_messages = True
          cursor_on_time = 0.7
          cursor_off_time = 0.5
          tab_spaces = 4
          blocked_mode = 2
          hide_spam = True
          keep_deleted = False
          limit_cache_deleted = 30
          tree_show_folders = True
          wrap_around = True
          mouse = True
          mouse_scroll_sensitivity = 3
          mouse_scroll_selection = False
          screen_update_delay = 0.01
          extra_line_delay = 5
          tenor_gif_type = 1
          trim_embed_url_size = 40
          aspell_mode = "normal"
          aspell_lang = "en_US"
          media_mute = False
          media_cap_fps = 30
          rpc_external = True
          emoji_as_text = False
          message_spacing = True
          native_media_player = True
          native_file_dialog = "auto"
          save_summaries = True
          default_stickers = True
          only_one_open_server = False
          assist = True
          assist_skip_app_command = False
          assist_limit = 50
          assist_score_cutoff = 15
          limit_command_history = 50
          game_detection_download_delay = 7
          downloads_path = None
          linux_notification_sound = "message"
          custom_notification_sound = None
          linux_ringtone_incoming = "phone-incoming-call"
          custom_ringtone_incoming = None
          linux_ringtone_outgoing = "phone-outgoing-calling"
          custom_ringtone_outgoing = None
          external_editor = None
          calls = True
          yt_dlp_path = "yt-dlp"
          yt_dlp_format = 18
          mpv_path = "mpv"
          yt_in_mpv = False
          client_properties = "default"
          custom_user_agent = None
          send_x_super_properties = True
          proxy = None
          custom_host = None
          capabilities = None
          easter_eggs = True
          debug = False

          [theme]
          compact = False
          tree_width = 32
          extra_window_height = 6
          member_list_width = 20
          format_message = "[%timestamp] <%global_name> | %content %edited"
          format_newline = "                       %content"
          format_reply = "[REPLY] <%global_name> | ╭──🡲 [%timestamp] %content"
          format_reactions = "[REACT]                ╰──⤙ %reactions"
          format_interaction = "                       ╭──⤙ %global_name used [%command]"
          format_one_reaction = "%count:%reaction"
          format_timestamp = "%H:%M"
          format_status_line_l = " %global_name (%username) - %status %afk %unreads %action %typing"
          format_status_line_r = "%vim_mode %slowmode"
          format_title_line_l = " %server: %channel"
          format_title_line_r = "%tabs"
          format_title_tree = " endcord  %task"
          format_rich = "%type %name - %state - %details"
          format_tabs = "%num - %name"
          format_prompt = "[%channel] > "
          format_forum = "[%timestamp] - <%msg_count> - %thread_name"
          format_forum_timestamp = "%Y-%m-%d"
          format_search_message = "%channel: [%date] <%global_name> | %content"
          edited_string = "(edited)"
          quote_character = "║"
          reactions_separator = "; "
          tabs_separator = " | "
          chat_date_separator = "─"
          format_date = " %B %d, %Y "
          limit_username = 10
          limit_channel_name = 15
          limit_typing_string = 30
          limit_prompt = 15
          limit_thread_name = 0
          limit_tab_len = 12
          limit_tabs_string = 60
          tree_vert_line = "│"
          tree_drop_down_vline = "│"
          tree_drop_down_hline = "─"
          tree_drop_down_intersect = "├"
          tree_drop_down_corner = "╰"
          tree_drop_down_pointer = "🡲"
          tree_drop_down_thread = "⤙"
          tree_drop_down_forum = "◆"
          tree_drop_down_folder = "+"
          tree_dm_status = "●"
          border_corners = "╭╰╮╯"
          username_role_colors = True
          color_default = [-1, -1]
          color_chat_mention = [223, 234]
          color_chat_blocked = [242, -1]
          color_chat_deleted = [95, -1]
          color_chat_pending = [242, -1]
          color_chat_selected = [233, 255]
          color_chat_separator = [242, -1, 'i']
          color_status_line = [233, 255]
          color_extra_line = [233, 245]
          color_title_line = [233, 255]
          color_extra_window = [-1, -1]
          color_prompt = [255, -1]
          color_input_line = [255, -1]
          color_cursor = [233, 255]
          color_misspelled = [222, -1]
          color_tree_default = [255, -1]
          color_tree_selected = [233, 255]
          color_tree_muted = [242, -1]
          color_tree_active = [255, 234]
          color_tree_unseen = [255, -1, 'b']
          color_tree_mentioned = [197, -1]
          color_tree_active_mentioned = [197, 234]
          color_format_message = [[-1, -1], [242, -2, 0, 0, 7], [25, -2, 0, 8, 9], [25, -2, 0, 19, 20], [-1, -2, 0, 21, 22]]
          color_format_newline = None
          color_format_reply = [[245, -1], [67, -2, 0, 0, 7], [25, -2, 0, 8, 9], [25, -2, 0, 19, 20], [-1, -2, 0, 21, 27]]
          color_format_reactions = [[245, -1], [131, -2, 0, 0, 7], [-1, -2, 0, 23, 27]]
          color_format_forum = [[-1, -1], [242, -2, 0, 0, 12], [25, -2, 0, 15, 20]]
          color_chat_standout = [153, 234]
          color_chat_edited = [241, -1]
          color_chat_url = [153, -1, 'u']
          color_chat_spoiler = [245, -1]
          color_chat_code = [250, 233]
          media_use_blocks = False
          media_ascii_palette = "  ..',;:c*loexk#O0XNW"
          media_saturation = 1.2
          media_font_aspect_ratio = 2.25
          media_color_bg = 16
          media_bar_ch = "━"

          [keybindings]
          tree_up = 575
          tree_down = 534
          tree_select = 0
          tree_collapse_threads = "ALT+104"
          tree_join_thread = "ALT+106"
          channel_info = "ALT+105"
          copy_channel_link = "ALT+85"
          input_left = 260
          input_right = 261
          word_left = 554
          word_right = 569
          select_left = 393
          select_right = 402
          select_word_left = 555
          select_word_right = 570
          insert_newline = 14
          undo = "ALT+122"
          redo = "ALT+90"
          select_all = "ALT+97"
          copy_sel = "ALT+99"
          cut_sel = "ALT+120"
          delete_word = 8
          send_message = 10
          chat_up = 259
          chat_down = 258
          reply = 18
          edit = 5
          delete = 4
          toggle_ping = 16
          scroll_bottom = 2
          go_replied = 7
          download = 23
          upload = 21
          browser = 15
          copy_msg = 12
          view_media = 22
          spoil = "ALT+116"
          search = 6
          search_gif = "ALT+102"
          profile_info = "ALT+112"
          copy_message_link = "ALT+117"
          add_reaction = "ALT+114"
          show_reactions = "ALT+119"
          show_pinned = "ALT+110"
          attach_prev = "ALT+44"
          attach_next = "ALT+46"
          extra_up = 573
          extra_down = 532
          extra_select = "ALT+10"
          preview_upload = "ALT+118"
          media_pause = 32
          media_replay = 122
          media_seek_forward = 261
          media_seek_backward = 260
          command_palette = 31
          cancel = 24
          cycle_status = "ALT+100"
          toggle_member_list = "ALT+109"
          toggle_tab = 20
          switch_tab_modifier = "ALT+NUM"
          open_external_editor = "ALT+101"
          quit = None

          [command_bindings]
          552 = "switch_tab prev"
          567 = "switch_tab next"
          11 = "command_palette; type 'goto '"
          336 = "tree_select server; collapse_all_except selected"
          337 = "tree_select server prev; collapse_all_except selected"
        '';
      };
    };
  };
}
