{ pkgs, ... }:
{
  retroarch = pkgs.wrapRetroArch {
    cores = with pkgs.libretro; [
      nestopia
      bsnes
      mupen64plus
      gambatte
      mgba
      melonds
      genesis-plus-gx
      picodrive
      beetle-saturn
      flycast
      beetle-psx-hw
      pcsx2
      ppsspp
      stella
      beetle-pce-fast
      beetle-supergrafx
      atari800
      prosystem
      handy
      virtualjaguar
      hatari
      beetle-vb
      gw
      pokemini
      beetle-ngp
      beetle-wswan
      bluemsx
      vice-x64
      vice-xplus4
      vice-xvic
      puae
      freeintv
      vecx
      o2em
      np2kai
      fuse
    ];
  };
}
