;;; noctalia-theme.el --- Eldritch colorscheme -*- lexical-binding: t -*-

;; Package-Requires: ((emacs "24.1"))

;;; Code:

(deftheme noctalia "Eldritch colorscheme.")

(let* ((bg "#212337")
      (err "#f16c75")
      (err-container "#a8020d")
      (on-background "#ebfafa")
      (on-err "#171928")
      (on-err-container "#fbd0d3")
      (on-primary "#171928")
      (on-primary-container "#cffce6")
      (on-secondary "#171928")
      (on-secondary-container "#cdf6fe")
      (on-surface "#ebfafa")
      (on-surface-variant "#abb4da")
      (on-tertiary "#171928")
      (on-tertiary-container "#dbd1fa")
      (outline-color "#606b9d")
      (outline-variant "#434b6e")
      (primary "#37f499")
      (primary-container "#00793e")
      (secondary "#04d1f9")
      (secondary-container "#00404c")
      (shadow "#414868")
      (surface "#212337")
      (surface-container "#292e42")
      (surface-container-high "#31374f")
      (surface-container-highest "#39405b")
      (surface-container-low "#25283c")
      (surface-container-lowest "#222539")
      (surface-variant "#292e42")
      (tertiary "#a48cf2")
      (tertiary-container "#3305c6")
      (success "#a48cf2")
      (on-success "#171928")
      (success-container "#3305c6")
      (on-success-container "#dbd1fa")
      (primary-fixed "#37f499")
      (primary-fixed-dim "#00793e")
      (secondary-fixed "#04d1f9")
      (secondary-fixed-dim "#00404c")
      (tertiary-fixed "#a48cf2")
      (tertiary-fixed-dim "#3305c6")
      (on-primary-fixed "#171928")
      (on-secondary-fixed "#171928")
      (on-tertiary-fixed "#171928"))

  (custom-theme-set-faces
   'noctalia
   `(default ((t (:background ,bg :foreground ,on-background))))
   `(cursor ((t (:background ,primary))))
   `(highlight ((t (:background ,surface-container-high))))
   `(region ((t (:background ,primary-container :foreground ,on-primary-container :extend t))))
   `(secondary-selection ((t (:background ,secondary-container :foreground ,on-secondary-container :extend t))))
   `(isearch ((t (:background ,tertiary-container :foreground ,on-tertiary-container :weight bold))))
   `(lazy-highlight ((t (:background ,secondary-container :foreground ,on-secondary-container))))
   `(vertical-border ((t (:foreground ,outline-color))))
   `(border ((t (:background ,outline-color :foreground ,outline-color))))
   `(window-divider ((t (:foreground ,secondary))))
   `(window-divider-first-pixel ((t (:foreground ,secondary))))
   `(window-divider-last-pixel ((t (:foreground ,secondary))))
   `(fringe ((t (:background ,surface :foreground ,outline-variant))))
   `(shadow ((t (:foreground ,outline-variant))))
   `(link ((t (:foreground ,primary :underline t))))
   `(link-visited ((t (:foreground ,tertiary :underline t))))
   `(success ((t (:foreground ,success))))
   `(warning ((t (:foreground ,secondary))))
   `(error ((t (:foreground ,err))))
   `(match ((t (:background ,secondary-container :foreground ,on-secondary-container))))
   `(font-lock-builtin-face ((t (:foreground ,primary))))
   `(font-lock-comment-face ((t (:foreground ,outline-color :slant italic))))
   `(font-lock-comment-delimiter-face ((t (:foreground ,outline-variant))))
   `(font-lock-constant-face ((t (:foreground ,tertiary :weight bold))))
   `(font-lock-doc-face ((t (:foreground ,on-surface-variant :slant italic))))
   `(font-lock-function-name-face ((t (:foreground ,primary :weight bold))))
   `(font-lock-keyword-face ((t (:foreground ,secondary :weight bold))))
   `(font-lock-string-face ((t (:foreground ,tertiary))))
   `(font-lock-type-face ((t (:foreground ,primary-fixed))))
   `(font-lock-variable-name-face ((t (:foreground ,on-surface))))
   `(font-lock-warning-face ((t (:foreground ,err :weight bold))))
   `(font-lock-preprocessor-face ((t (:foreground ,secondary-fixed-dim))))
   `(font-lock-negation-char-face ((t (:foreground ,tertiary-fixed))))
   `(show-paren-match ((t (:background ,primary-container :foreground ,on-primary-container :weight bold))))
   `(show-paren-mismatch ((t (:background ,err-container :foreground ,on-err-container :weight bold))))
   `(mode-line ((t (:background ,surface-container-high :foreground ,on-surface :box nil))))
   `(mode-line-inactive ((t (:background ,surface :foreground ,on-surface-variant :box nil))))
   `(mode-line-buffer-id ((t (:foreground ,primary :weight bold))))
   `(mode-line-emphasis ((t (:foreground ,primary :weight bold))))
   `(mode-line-highlight ((t (:foreground ,primary :box nil))))
   `(org-block ((t (:background ,surface-container-low :extend t :inherit fixed-pitch))))
   `(org-block-begin-line ((t (:background ,surface-container-low :foreground ,primary-fixed-dim :extend t :slant italic :inherit fixed-pitch))))
   `(org-block-end-line ((t (:background ,surface-container-low :foreground ,primary-fixed-dim :extend t :slant italic :inherit fixed-pitch))))
   `(org-level-1 ((t (:foreground ,primary :weight bold :height 1.2))))
   `(org-level-2 ((t (:foreground ,secondary :weight bold :height 1.1))))
   `(org-level-3 ((t (:foreground ,tertiary :weight bold))))
   `(org-todo ((t (:foreground ,err :weight bold))))
   `(org-done ((t (:foreground ,success :weight bold))))
   `(which-key-key-face ((t (:foreground ,primary :weight bold))))
   `(which-key-separator-face ((t (:foreground ,outline-variant))))
   `(which-key-command-description-face ((t (:foreground ,on-surface))))
   `(which-key-group-description-face ((t (:foreground ,secondary))))
   `(which-key-special-key-face ((t (:foreground ,tertiary :weight bold))))
   `(line-number ((t (:foreground ,outline-variant :inherit fixed-pitch))))
   `(line-number-current-line ((t (:foreground ,primary :weight bold :inherit fixed-pitch))))
   `(dired-directory ((t (:foreground ,primary :weight bold))))
   `(dired-symlink ((t (:foreground ,secondary :slant italic))))
   `(dired-flagged ((t (:foreground ,err))))
   `(markdown-header-face-1 ((t (:foreground ,primary :weight bold :height 1.2))))
   `(markdown-header-face-2 ((t (:foreground ,primary-container :weight bold :height 1.1))))
   `(markdown-header-face-3 ((t (:foreground ,secondary :weight bold))))
   `(markdown-inline-code-face ((t (:foreground ,tertiary-fixed :background ,surface-container-low :inherit fixed-pitch))))
   `(markdown-code-face ((t (:background ,surface-container-low :extend t :inherit fixed-pitch))))
   `(flycheck-error ((t (:underline (:style wave :color ,err)))))
   `(flycheck-warning ((t (:underline (:style wave :color ,secondary)))))
   `(flycheck-info ((t (:underline (:style wave :color ,tertiary)))))
   `(minibuffer-prompt ((t (:foreground ,primary :weight bold))))
   `(lsp-face-highlight-textual ((t (:background ,primary-container :foreground ,on-primary-container :weight bold))))
   `(lsp-face-highlight-read ((t (:background ,secondary-container :foreground ,on-secondary-container :weight bold))))
   `(lsp-face-highlight-write ((t (:background ,tertiary-container :foreground ,on-tertiary-container :weight bold))))
   `(tab-bar ((t (:background ,surface-container-high :foreground ,on-surface :box nil))))
   `(tab-bar-tab ((t (:background ,surface-container-high :foreground ,on-surface :weight bold :box nil))))
   `(tab-bar-tab-inactive ((t (:background ,surface :foreground ,on-surface-variant :box nil))))
   `(centaur-tabs-default ((t (:background ,surface-container-high :foreground ,on-surface))))
   `(centaur-tabs-selected ((t (:background ,surface-container-high :foreground ,on-surface :weight bold))))
   `(centaur-tabs-unselected ((t (:background ,surface :foreground ,on-surface-variant))))
   `(centaur-tabs-selected-modified ((t (:background ,surface-container-high :foreground ,tertiary :weight bold))))
   `(centaur-tabs-unselected-modified ((t (:background ,surface :foreground ,tertiary))))
   `(centaur-tabs-active-bar-face ((t (:background ,primary))))
   `(corfu-default ((t (:background ,surface-container :foreground ,on-surface))))
   `(corfu-current ((t (:background ,primary-container :foreground ,on-primary-container))))
   `(corfu-bar ((t (:background ,primary))))
   `(corfu-border ((t (:background ,outline-variant))))
   `(fixed-pitch ((t (:family "monospace"))))
   `(variable-pitch ((t (:family "sans serif"))))
   ;; vterm -- exact noctalia ANSI palette from ghostty theme
   `(vterm-color-default       ((t (:foreground "#ebfafa" :background "#212337"))))
   `(vterm-color-black         ((t (:foreground "#21222c" :background "#21222c"))))
   `(vterm-color-red           ((t (:foreground "#f9515d" :background "#f9515d"))))
   `(vterm-color-green         ((t (:foreground "#37f499" :background "#37f499"))))
   `(vterm-color-yellow        ((t (:foreground "#e9f941" :background "#e9f941"))))
   `(vterm-color-blue          ((t (:foreground "#9071f4" :background "#9071f4"))))
   `(vterm-color-magenta       ((t (:foreground "#f265b5" :background "#f265b5"))))
   `(vterm-color-cyan          ((t (:foreground "#04d1f9" :background "#04d1f9"))))
   `(vterm-color-white         ((t (:foreground "#ebfafa" :background "#ebfafa"))))
   `(vterm-color-bright-black  ((t (:foreground "#7081d0" :background "#7081d0"))))
   `(vterm-color-bright-red    ((t (:foreground "#f16c75" :background "#f16c75"))))
   `(vterm-color-bright-green  ((t (:foreground "#69f8b3" :background "#69f8b3"))))
   `(vterm-color-bright-yellow ((t (:foreground "#f1fc79" :background "#f1fc79"))))
   `(vterm-color-bright-blue   ((t (:foreground "#a48cf2" :background "#a48cf2"))))
   `(vterm-color-bright-magenta ((t (:foreground "#fd92ce" :background "#fd92ce"))))
   `(vterm-color-bright-cyan   ((t (:foreground "#66e4fd" :background "#66e4fd"))))
   `(vterm-color-bright-white  ((t (:foreground "#ffffff" :background "#ffffff"))))))

(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'noctalia)
;;; noctalia-theme.el ends here
